### ISSUE TITLE
Unable to connect to ASR920

### ISSUE THREAD

**Issue by TrivialPants** [hpreston/demo_mac_to_interface_tool#1]
Hi Hank,

I am trying to connect to an ASR920 running IOS XE but don't see the platform listed in the pyats testbed documentation. So I left the platform key blank in the yaml file. I get the following error:

I tried the following in my testbed.yaml file:

devices: 
    asr-920-24:
        type: 'router'
        os: 'iosxe'
        alias: 'test'
        credentials:
            default:
                username: [redacted]
                password: [redacted]
        connections:
            cli:
                protocol: telnet
                ip: "[redacted]"

I get the following error:

Traceback (most recent call last):
  File "mac_lookup.py", line 295, in <module>
    layer3_devices = find_layer3_devices(testbed, args.layer3_devices)
  File "mac_lookup.py", line 62, in find_layer3_devices
    for name in layer3_devices_list:
TypeError: 'NoneType' object is not iterable

**Comment by TrivialPants** [comment]
Nevermind - I read your blog at https://blogs.cisco.com/developer/ask-hank-how-can-i-automate-a-mac-address-interface-report more closely & read that I need to input the name of the device from the testbed file to allow it to connect.

Closing the issue request! Thanks for the tool!
